version: '3.8'
services:
  proxy:
    image: nginx:mainline
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "8080:80"
  client:
    image: "1"
    build:
      context: .
      dockerfile: D:\GitHub\Staff_NETR\reactapp\Dockerfile