version: '3.8'
services:
  proxy:
    image: nginx:1.18.0-alpine
    #image: nginx:mainline
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "8080:80"
  client:
    #image: "1"
    build: H:\source\repos\client
      #context: H:\source\repos\WeatherApp\reactapp
      #dockerfile: H:\source\repos\WeatherApp\reactapp
    #ports:
    #  - "3001:80"
  webapi:
    build: H:\source\repos\WebApplication3
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
